language: scala

scala:
  - 2.10.4
  - 2.11.2

jdk:
  - openjdk7
  - oraclejdk7

before_script:
  - sh src/test/resources/setup_travis.sh

matrix:
  include:
  - scala: 2.12.0-RC1
    jdk: oraclejdk8
